// <auto-generated />
using System;
using Clinic.Infrastructure.Presistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinic.Infrastructure.Presistence.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clinic.Core.Domin.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "01961d25-b4da-7184-a2a8-765486bd4857",
                            ConcurrencyStamp = "EAE00686-2608-4516-AD1B-F96CD87C475E",
                            CreatedAt = new DateTime(2025, 6, 2, 18, 8, 18, 544, DateTimeKind.Utc).AddTicks(2188),
                            IsDeleted = false,
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "01961d25-b4da-75a5-a1f4-a7aa10e421ed",
                            ConcurrencyStamp = "386C6E14-D0FD-40FF-80D0-74B419360EF0",
                            CreatedAt = new DateTime(2025, 6, 2, 18, 8, 18, 544, DateTimeKind.Utc).AddTicks(4809),
                            IsDeleted = false,
                            Name = "Pharmacist",
                            NormalizedName = "PHARMACIST"
                        },
                        new
                        {
                            Id = "01961d25-b4da-71e9-a488-1b8db232e984",
                            ConcurrencyStamp = "1420D50C-F54D-4503-88E8-A2EFA3BD7137",
                            CreatedAt = new DateTime(2025, 6, 2, 18, 8, 18, 544, DateTimeKind.Utc).AddTicks(4843),
                            IsDeleted = false,
                            Name = "LabTechnician",
                            NormalizedName = "LABTECHNICIAN"
                        },
                        new
                        {
                            Id = "01961d25-b4da-72bb-a3a9-7e102ec2be31",
                            ConcurrencyStamp = "CC350D3E-101D-4AA1-B2C9-5D92D13FD38E",
                            CreatedAt = new DateTime(2025, 6, 2, 18, 8, 18, 544, DateTimeKind.Utc).AddTicks(4854),
                            IsDeleted = false,
                            Name = "Receptionist",
                            NormalizedName = "RECEPTIONIST"
                        },
                        new
                        {
                            Id = "01961d25-b4da-9999-a1b2-123456789abc",
                            ConcurrencyStamp = "A3C5D9C2-7F54-4A2C-8456-9E6C7E8B1E2A",
                            CreatedAt = new DateTime(2025, 6, 2, 18, 8, 18, 544, DateTimeKind.Utc).AddTicks(4863),
                            IsDeleted = false,
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WhatsAppNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DoctorId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PatientId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<int>("appointmentType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("DoctorId1");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientId1");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.AvailableLabTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabTechnicianId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LabTechnicianId");

                    b.ToTable("AvailableLabTests");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosisText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.LabTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableLabTestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TestResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvailableLabTestId");

                    b.HasIndex("VisitId");

                    b.ToTable("LabTests");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PharmacistId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PharmacistId");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PrescriptionStatus")
                        .HasColumnType("int");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.TreatmentMedicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("TreatmentMedicines");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("LabTechnicianId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PharmacistId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReceptionistId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LabTechnicianId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PharmacistId");

                    b.HasIndex("ReceptionistId");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.WorkingDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("DoctorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabTechnicianId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PharmacistId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LabTechnicianId");

                    b.HasIndex("PharmacistId");

                    b.ToTable("WorkingDays");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "permissions",
                            ClaimValue = "Appointments:ViewAppointments",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "permissions",
                            ClaimValue = "Appointments:AddAppointments",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "permissions",
                            ClaimValue = "Appointments:UpdateAppointments",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "permissions",
                            ClaimValue = "Appointments:DeleteAppointments",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "permissions",
                            ClaimValue = "Visits:ViewVisits",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "permissions",
                            ClaimValue = "Visits:AddVisits",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "permissions",
                            ClaimValue = "Visits:UpdateVisits",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "permissions",
                            ClaimValue = "Visits:DeleteVisits",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "permissions",
                            ClaimValue = "Patients:ViewPatients",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "permissions",
                            ClaimValue = "Patients:AddPatients",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "permissions",
                            ClaimValue = "Patients:UpdatePatients",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "permissions",
                            ClaimValue = "Patients:DeletePatients",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "permissions",
                            ClaimValue = "Doctors:ViewDoctors",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "permissions",
                            ClaimValue = "Doctors:AddDoctors",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "permissions",
                            ClaimValue = "Doctors:UpdateDoctors",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "permissions",
                            ClaimValue = "Doctors:DeleteDoctors",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "permissions",
                            ClaimValue = "Receptionists:ViewReceptionists",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "permissions",
                            ClaimValue = "Receptionists:AddReceptionists",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "permissions",
                            ClaimValue = "Receptionists:UpdateReceptionists",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "permissions",
                            ClaimValue = "Receptionists:DeleteReceptionists",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "permissions",
                            ClaimValue = "Pharmacists:ViewPharmacists",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "permissions",
                            ClaimValue = "Pharmacists:AddPharmacists",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "permissions",
                            ClaimValue = "Pharmacists:UpdatePharmacists",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "permissions",
                            ClaimValue = "Pharmacists:DeletePharmacists",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "permissions",
                            ClaimValue = "LabTechnicians:ViewLabTechnicians",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "permissions",
                            ClaimValue = "LabTechnicians:AddLabTechnicians",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "permissions",
                            ClaimValue = "LabTechnicians:UpdateLabTechnicians",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "permissions",
                            ClaimValue = "LabTechnicians:DeleteLabTechnicians",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "permissions",
                            ClaimValue = "Diagnoses:ViewDiagnoses",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "permissions",
                            ClaimValue = "Diagnoses:AddDiagnoses",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 31,
                            ClaimType = "permissions",
                            ClaimValue = "Diagnoses:UpdateDiagnoses",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 32,
                            ClaimType = "permissions",
                            ClaimValue = "Diagnoses:DeleteDiagnoses",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 33,
                            ClaimType = "permissions",
                            ClaimValue = "Treatments:ViewTreatments",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 34,
                            ClaimType = "permissions",
                            ClaimValue = "Treatments:AddTreatments",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 35,
                            ClaimType = "permissions",
                            ClaimValue = "Treatments:UpdateTreatments",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 36,
                            ClaimType = "permissions",
                            ClaimValue = "Treatments:DeleteTreatments",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 37,
                            ClaimType = "permissions",
                            ClaimValue = "Medicines:ViewMedicines",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 38,
                            ClaimType = "permissions",
                            ClaimValue = "Medicines:AddMedicines",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 39,
                            ClaimType = "permissions",
                            ClaimValue = "Medicines:UpdateMedicines",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 40,
                            ClaimType = "permissions",
                            ClaimValue = "Medicines:DeleteMedicines",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 41,
                            ClaimType = "permissions",
                            ClaimValue = "LabTests:ViewLabTests",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 42,
                            ClaimType = "permissions",
                            ClaimValue = "LabTests:AddLabTests",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 43,
                            ClaimType = "permissions",
                            ClaimValue = "LabTests:UpdateLabTests",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 44,
                            ClaimType = "permissions",
                            ClaimValue = "LabTests:DeleteLabTests",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 45,
                            ClaimType = "permissions",
                            ClaimValue = "WorkingDays:ViewWorkingDays",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 46,
                            ClaimType = "permissions",
                            ClaimValue = "WorkingDays:AddWorkingDays",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 47,
                            ClaimType = "permissions",
                            ClaimValue = "WorkingDays:UpdateWorkingDays",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 48,
                            ClaimType = "permissions",
                            ClaimValue = "WorkingDays:DeleteWorkingDays",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 49,
                            ClaimType = "permissions",
                            ClaimValue = "AvailableLabTest:ViewAvailableLabTests",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 50,
                            ClaimType = "permissions",
                            ClaimValue = "AvailableLabTest:AddAvailableLabTests",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 51,
                            ClaimType = "permissions",
                            ClaimValue = "AvailableLabTest:UpdateAvailableLabTests",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 52,
                            ClaimType = "permissions",
                            ClaimValue = "AvailableLabTest:DeleteAvailableLabTests",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 53,
                            ClaimType = "permissions",
                            ClaimValue = "UserNotification:ViewUserNotifications",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 54,
                            ClaimType = "permissions",
                            ClaimValue = "UserNotification:DeleteUserNotifications",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            Id = 55,
                            ClaimType = "permissions",
                            ClaimValue = "Appointments:AddAppointments",
                            RoleId = "01961d25-b4da-72bb-a3a9-7e102ec2be31"
                        },
                        new
                        {
                            Id = 56,
                            ClaimType = "permissions",
                            ClaimValue = "Appointments:ViewAppointments",
                            RoleId = "01961d25-b4da-72bb-a3a9-7e102ec2be31"
                        },
                        new
                        {
                            Id = 57,
                            ClaimType = "permissions",
                            ClaimValue = "Appointments:UpdateAppointments",
                            RoleId = "01961d25-b4da-72bb-a3a9-7e102ec2be31"
                        },
                        new
                        {
                            Id = 58,
                            ClaimType = "permissions",
                            ClaimValue = "Appointments:DeleteAppointments",
                            RoleId = "01961d25-b4da-72bb-a3a9-7e102ec2be31"
                        },
                        new
                        {
                            Id = 59,
                            ClaimType = "permissions",
                            ClaimValue = "UserNotification:ViewUserNotifications",
                            RoleId = "01961d25-b4da-72bb-a3a9-7e102ec2be31"
                        },
                        new
                        {
                            Id = 60,
                            ClaimType = "permissions",
                            ClaimValue = "UserNotification:DeleteUserNotifications",
                            RoleId = "01961d25-b4da-72bb-a3a9-7e102ec2be31"
                        },
                        new
                        {
                            Id = 61,
                            ClaimType = "permissions",
                            ClaimValue = "Medicines:AddMedicines",
                            RoleId = "01961d25-b4da-75a5-a1f4-a7aa10e421ed"
                        },
                        new
                        {
                            Id = 62,
                            ClaimType = "permissions",
                            ClaimValue = "Medicines:ViewMedicines",
                            RoleId = "01961d25-b4da-75a5-a1f4-a7aa10e421ed"
                        },
                        new
                        {
                            Id = 63,
                            ClaimType = "permissions",
                            ClaimValue = "Medicines:UpdateMedicines",
                            RoleId = "01961d25-b4da-75a5-a1f4-a7aa10e421ed"
                        },
                        new
                        {
                            Id = 64,
                            ClaimType = "permissions",
                            ClaimValue = "Medicines:DeleteMedicines",
                            RoleId = "01961d25-b4da-75a5-a1f4-a7aa10e421ed"
                        },
                        new
                        {
                            Id = 65,
                            ClaimType = "permissions",
                            ClaimValue = "Treatments:ViewTreatments",
                            RoleId = "01961d25-b4da-75a5-a1f4-a7aa10e421ed"
                        },
                        new
                        {
                            Id = 66,
                            ClaimType = "permissions",
                            ClaimValue = "UserNotification:ViewUserNotifications",
                            RoleId = "01961d25-b4da-75a5-a1f4-a7aa10e421ed"
                        },
                        new
                        {
                            Id = 67,
                            ClaimType = "permissions",
                            ClaimValue = "UserNotification:DeleteUserNotifications",
                            RoleId = "01961d25-b4da-75a5-a1f4-a7aa10e421ed"
                        },
                        new
                        {
                            Id = 68,
                            ClaimType = "permissions",
                            ClaimValue = "AvailableLabTest:AddAvailableLabTests",
                            RoleId = "01961d25-b4da-71e9-a488-1b8db232e984"
                        },
                        new
                        {
                            Id = 69,
                            ClaimType = "permissions",
                            ClaimValue = "AvailableLabTest:UpdateAvailableLabTests",
                            RoleId = "01961d25-b4da-71e9-a488-1b8db232e984"
                        },
                        new
                        {
                            Id = 70,
                            ClaimType = "permissions",
                            ClaimValue = "AvailableLabTest:DeleteAvailableLabTests",
                            RoleId = "01961d25-b4da-71e9-a488-1b8db232e984"
                        },
                        new
                        {
                            Id = 71,
                            ClaimType = "permissions",
                            ClaimValue = "AvailableLabTest:ViewAvailableLabTests",
                            RoleId = "01961d25-b4da-71e9-a488-1b8db232e984"
                        },
                        new
                        {
                            Id = 72,
                            ClaimType = "permissions",
                            ClaimValue = "LabTests:ViewLabTests",
                            RoleId = "01961d25-b4da-71e9-a488-1b8db232e984"
                        },
                        new
                        {
                            Id = 73,
                            ClaimType = "permissions",
                            ClaimValue = "LabTests:UpdateLabTests",
                            RoleId = "01961d25-b4da-71e9-a488-1b8db232e984"
                        },
                        new
                        {
                            Id = 74,
                            ClaimType = "permissions",
                            ClaimValue = "UserNotification:ViewUserNotifications",
                            RoleId = "01961d25-b4da-71e9-a488-1b8db232e984"
                        },
                        new
                        {
                            Id = 75,
                            ClaimType = "permissions",
                            ClaimValue = "UserNotification:DeleteUserNotifications",
                            RoleId = "01961d25-b4da-71e9-a488-1b8db232e984"
                        },
                        new
                        {
                            Id = 76,
                            ClaimType = "permissions",
                            ClaimValue = "Appointments:ViewAppointments",
                            RoleId = "01961d25-b4da-9999-a1b2-123456789abc"
                        },
                        new
                        {
                            Id = 77,
                            ClaimType = "permissions",
                            ClaimValue = "Appointments:AddAppointments",
                            RoleId = "01961d25-b4da-9999-a1b2-123456789abc"
                        },
                        new
                        {
                            Id = 78,
                            ClaimType = "permissions",
                            ClaimValue = "Visits:ViewVisits",
                            RoleId = "01961d25-b4da-9999-a1b2-123456789abc"
                        },
                        new
                        {
                            Id = 79,
                            ClaimType = "permissions",
                            ClaimValue = "WorkingDays:ViewWorkingDays",
                            RoleId = "01961d25-b4da-9999-a1b2-123456789abc"
                        },
                        new
                        {
                            Id = 80,
                            ClaimType = "permissions",
                            ClaimValue = "LabTests:ViewLabTests",
                            RoleId = "01961d25-b4da-9999-a1b2-123456789abc"
                        },
                        new
                        {
                            Id = 81,
                            ClaimType = "permissions",
                            ClaimValue = "Treatments:ViewTreatments",
                            RoleId = "01961d25-b4da-9999-a1b2-123456789abc"
                        },
                        new
                        {
                            Id = 82,
                            ClaimType = "permissions",
                            ClaimValue = "Diagnoses:ViewDiagnoses",
                            RoleId = "01961d25-b4da-9999-a1b2-123456789abc"
                        },
                        new
                        {
                            Id = 83,
                            ClaimType = "permissions",
                            ClaimValue = "UserNotification:ViewUserNotifications",
                            RoleId = "01961d25-b4da-9999-a1b2-123456789abc"
                        },
                        new
                        {
                            Id = 84,
                            ClaimType = "permissions",
                            ClaimValue = "UserNotification:DeleteUserNotifications",
                            RoleId = "01961d25-b4da-9999-a1b2-123456789abc"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "0195d439-9ca1-7873-9c14-a4bc1c201593",
                            RoleId = "01961d25-b4da-7184-a2a8-765486bd4857"
                        },
                        new
                        {
                            UserId = "0195d439-9ca1-7873-9c14-a4bc1c202222",
                            RoleId = "01961d25-b4da-75a5-a1f4-a7aa10e421ed"
                        },
                        new
                        {
                            UserId = "0195d439-9ca1-7873-9c14-a4bc1c203333",
                            RoleId = "01961d25-b4da-71e9-a488-1b8db232e984"
                        },
                        new
                        {
                            UserId = "0195d439-9ca1-7873-9c14-a4bc1c204444",
                            RoleId = "01961d25-b4da-72bb-a3a9-7e102ec2be31"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Users.Doctor", b =>
                {
                    b.HasBaseType("Clinic.Core.Domin.Entities.ApplicationUser");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsultationDurationInMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("FollowUpDurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Doctor");

                    b.HasData(
                        new
                        {
                            Id = "0195d439-9ca1-7873-9c14-a4bc1c201593",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0195d43b-a808-757b-9c3e-bf90c6091133",
                            CreatedAt = new DateTime(2025, 6, 2, 18, 8, 18, 529, DateTimeKind.Utc).AddTicks(789),
                            Email = "Weso430@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Weso Admin",
                            Gender = 0,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "WESO430@GMAIL.COM",
                            NormalizedUserName = "WESO430@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM43QmJkxKs66+hBHOfjYFSj/wGY6jR00ZSDdz9+hspCA5Jjn64fUvCcm0TrTcyoCQ==",
                            PhoneNumber = "01032500077",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0195d43be3f271878cc37be7dfc34361",
                            TwoFactorEnabled = false,
                            UserName = "Weso430@gmail.com",
                            Biography = "",
                            ConsultationDurationInMinutes = 30,
                            Degree = 1,
                            FollowUpDurationInMinutes = 15,
                            Specialization = "General"
                        });
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Users.LabTechnician", b =>
                {
                    b.HasBaseType("Clinic.Core.Domin.Entities.ApplicationUser");

                    b.HasDiscriminator().HasValue("LabTechnician");

                    b.HasData(
                        new
                        {
                            Id = "0195d439-9ca1-7873-9c14-a4bc1c203333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0195d43blab-conc",
                            CreatedAt = new DateTime(2025, 6, 2, 18, 8, 18, 544, DateTimeKind.Utc).AddTicks(66),
                            Email = "lab@clinic.com",
                            EmailConfirmed = true,
                            FullName = "Lab User",
                            Gender = 0,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LAB@CLINIC.COM",
                            NormalizedUserName = "LAB@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM43QmJkxKs66+hBHOfjYFSj/wGY6jR00ZSDdz9+hspCA5Jjn64fUvCcm0TrTcyoCQ==",
                            PhoneNumber = "01000000002",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0195d43blab-sec",
                            TwoFactorEnabled = false,
                            UserName = "lab@clinic.com"
                        });
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Users.Patient", b =>
                {
                    b.HasBaseType("Clinic.Core.Domin.Entities.ApplicationUser");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BloodType")
                        .HasColumnType("int");

                    b.Property<string>("NationalId")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.HasDiscriminator().HasValue("Patient");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Users.Pharmacist", b =>
                {
                    b.HasBaseType("Clinic.Core.Domin.Entities.ApplicationUser");

                    b.HasDiscriminator().HasValue("Pharmacist");

                    b.HasData(
                        new
                        {
                            Id = "0195d439-9ca1-7873-9c14-a4bc1c202222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0195d43bpharma-conc",
                            CreatedAt = new DateTime(2025, 6, 2, 18, 8, 18, 543, DateTimeKind.Utc).AddTicks(9117),
                            Email = "pharmacist@clinic.com",
                            EmailConfirmed = true,
                            FullName = "Pharma User",
                            Gender = 0,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PHARMACIST@CLINIC.COM",
                            NormalizedUserName = "PHARMACIST@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM43QmJkxKs66+hBHOfjYFSj/wGY6jR00ZSDdz9+hspCA5Jjn64fUvCcm0TrTcyoCQ==",
                            PhoneNumber = "01000000001",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0195d43bpharma-sec",
                            TwoFactorEnabled = false,
                            UserName = "pharmacist@clinic.com"
                        });
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Users.Receptionist", b =>
                {
                    b.HasBaseType("Clinic.Core.Domin.Entities.ApplicationUser");

                    b.Property<int?>("workShift")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Receptionist");

                    b.HasData(
                        new
                        {
                            Id = "0195d439-9ca1-7873-9c14-a4bc1c204444",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0195d43brecep-conc",
                            CreatedAt = new DateTime(2025, 6, 2, 18, 8, 18, 544, DateTimeKind.Utc).AddTicks(956),
                            Email = "receptionist@clinic.com",
                            EmailConfirmed = true,
                            FullName = "Reception User",
                            Gender = 0,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "RECEPTIONIST@CLINIC.COM",
                            NormalizedUserName = "RECEPTIONIST@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM43QmJkxKs66+hBHOfjYFSj/wGY6jR00ZSDdz9+hspCA5Jjn64fUvCcm0TrTcyoCQ==",
                            PhoneNumber = "01000000003",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0195d43brecep-sec",
                            TwoFactorEnabled = false,
                            UserName = "receptionist@clinic.com"
                        });
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Appointment", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.Users.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Core.Domin.Entities.Users.Doctor", null)
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId1");

                    b.HasOne("Clinic.Core.Domin.Entities.Users.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Core.Domin.Entities.Users.Patient", null)
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId1");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.AvailableLabTest", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.Users.LabTechnician", "LabTechnician")
                        .WithMany("AvailableLabTests")
                        .HasForeignKey("LabTechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabTechnician");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Diagnosis", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.Visit", "Visit")
                        .WithMany("Diagnoses")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.LabTest", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.AvailableLabTest", "AvailableLabTest")
                        .WithMany("LabTests")
                        .HasForeignKey("AvailableLabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic.Core.Domin.Entities.Visit", "Visit")
                        .WithMany("LabTests")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailableLabTest");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Medicine", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.Users.Pharmacist", "Pharmacist")
                        .WithMany("Medicines")
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Treatment", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.Visit", "Visit")
                        .WithMany("Treatments")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.TreatmentMedicine", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.Medicine", "Medicine")
                        .WithMany("TreatmentMedicines")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic.Core.Domin.Entities.Treatment", "Treatment")
                        .WithMany("TreatmentMedicines")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.UserNotification", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.Users.Doctor", null)
                        .WithMany("UserNotifications")
                        .HasForeignKey("DoctorId");

                    b.HasOne("Clinic.Core.Domin.Entities.Users.LabTechnician", null)
                        .WithMany("UserNotifications")
                        .HasForeignKey("LabTechnicianId");

                    b.HasOne("Clinic.Core.Domin.Entities.Users.Patient", null)
                        .WithMany("UserNotifications")
                        .HasForeignKey("PatientId");

                    b.HasOne("Clinic.Core.Domin.Entities.Users.Pharmacist", null)
                        .WithMany("UserNotifications")
                        .HasForeignKey("PharmacistId");

                    b.HasOne("Clinic.Core.Domin.Entities.Users.Receptionist", null)
                        .WithMany("UserNotifications")
                        .HasForeignKey("ReceptionistId");

                    b.HasOne("Clinic.Core.Domin.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Visit", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.Appointment", "Appointment")
                        .WithOne("Visit")
                        .HasForeignKey("Clinic.Core.Domin.Entities.Visit", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic.Core.Domin.Entities.Users.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic.Core.Domin.Entities.Users.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.WorkingDay", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.Users.Doctor", "Doctor")
                        .WithMany("WorkingDays")
                        .HasForeignKey("DoctorId");

                    b.HasOne("Clinic.Core.Domin.Entities.Users.LabTechnician", "LabTechnician")
                        .WithMany("WorkingDays")
                        .HasForeignKey("LabTechnicianId");

                    b.HasOne("Clinic.Core.Domin.Entities.Users.Pharmacist", "Pharmacist")
                        .WithMany("WorkingDays")
                        .HasForeignKey("PharmacistId");

                    b.Navigation("Doctor");

                    b.Navigation("LabTechnician");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic.Core.Domin.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Clinic.Core.Domin.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Appointment", b =>
                {
                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.AvailableLabTest", b =>
                {
                    b.Navigation("LabTests");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Medicine", b =>
                {
                    b.Navigation("TreatmentMedicines");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Treatment", b =>
                {
                    b.Navigation("TreatmentMedicines");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Visit", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("LabTests");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Users.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("UserNotifications");

                    b.Navigation("WorkingDays");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Users.LabTechnician", b =>
                {
                    b.Navigation("AvailableLabTests");

                    b.Navigation("UserNotifications");

                    b.Navigation("WorkingDays");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Users.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("UserNotifications");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Users.Pharmacist", b =>
                {
                    b.Navigation("Medicines");

                    b.Navigation("UserNotifications");

                    b.Navigation("WorkingDays");
                });

            modelBuilder.Entity("Clinic.Core.Domin.Entities.Users.Receptionist", b =>
                {
                    b.Navigation("UserNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
